spring:
  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 10MB

ocr:
  save-dir: uploads

translate:
  default-lang: ko

translation:
  google:
    api-key: [발급된 키]
